name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - black
  - bleach
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cryptography
  - cycler
  - cytoolz
  - dataclasses
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - flit-core
  - freetype
  - giflib
  - gmp
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - isl
  - jbig
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - lcms2
  - ldid
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libiconv
  - liblapack
  - libllvm12
  - libopenblas
  - libpng
  - libsodium
  - libtiff
  - libwebp
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - llvm-tools
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mpc
  - mpfr
  - munkres
  - mypy_extensions
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pathspec
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python=3.9
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - readline
  - requests
  - send2trash
  - setuptools
  - six
  - sniffio
  - sqlite
  - stack_data
  - tapi
  - terminado
  - testpath
  - tk
  - tomli
  - toolz
  - tornado
  - traitlets
  - typed-ast
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - scipy
  - sympy
  - pip:
    - aenum
    - astunparse
    - boltons
    - cached-property
    - dace
    - devtools
    - dill
    - distro
    - flask
    - itsdangerous
    - mako
    - mpmath
    - networkx
    - ply
    - pybind11
    - pydantic
    - pyyaml
    - scikit-build
    - tabulate
    - typing-inspect
    - websockets
    - werkzeug
    - xxhash>=1.4.4
    - git+https://github.com/gridtools/gt4py.git